// Generated by CoffeeScript 1.7.1
var BearSchema, mongoose;

mongoose = require('mongoose');

BearSchema = new mongoose.Schema({
  name: String
});

module.exports = mongoose.model('Bear', BearSchema);
