// Generated by CoffeeScript 1.7.1
var Product, app, bodyParser, express, mongoose, port, router;

express = require('express');

bodyParser = require('body-parser');

mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/tienda');

Product = require('./models/product');

app = express();

app.use(bodyParser());

port = process.env.PORT || 8080;

router = express.Router();

router.use(function(req, res, next) {
  res.setHeader('Access-Control-Allow-Origin', 'http://tienda.mk');
  res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
  return next();
});

router.get('/', function(req, res) {
  return res.json({
    message: "llamado al server"
  });
});

router.route('/products').post(function(req, res) {
  var product;
  product = new Product();
  product.img = req.body.img;
  product.name = req.body.name;
  product.description = req.body.description;
  product.price = req.body.price;
  product.size.long = req.body.size.long;
  product.size.width = req.body.size.width;
  product.size.height = req.body.size.height;
  return product.save(function(err) {
    if (err) {
      res.send(err);
      console.log("error");
    }
    return res.json({
      message: 'product created!'
    });
  });
}).get(function(req, res) {
  return Product.find(function(err, products) {
    if (err) {
      res.send(err);
    }
    return res.json(products);
  });
});

app.use('/api', router);

app.listen(port);

console.log("upa!");
