// Generated by CoffeeScript 1.7.1
var Bear, app, bodyParser, express, mongoose, port, router;

express = require('express');

bodyParser = require('body-parser');

mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/test');

Bear = require('./models/bear');

app = express();

app.use(bodyParser());

port = process.env.PORT || 8080;

router = express.Router();

router.use(function(req, res, next) {
  console.log("asdasd2");
  res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
  return next();
});

router.get('/', function(req, res) {
  return res.json({
    message: "asdasd"
  });
});

router.route('/bears').post(function(req, res) {
  var bear;
  bear = new Bear();
  bear.name = req.body.name;
  console.log(bear.name);
  return bear.save(function(err) {
    if (err) {
      res.send(err);
      console.log("error");
    }
    return res.json({
      message: 'bear created!'
    });
  });
}).get(function(req, res) {
  return Bear.find(function(err, bears) {
    if (err) {
      res.send(err);
    }
    return res.json(bears);
  });
});

app.use('/api', router);

app.listen(port);

console.log("arriba");
