// Generated by CoffeeScript 1.7.1
router.route('/bears').post(function(req, res) {
  var bear;
  bear = new Bear();
  bear.name = req.body.name;
  return bear.save(function(err) {
    if (err) {
      res.send(err);
    }
    return res.json({
      message: 'bear created!'
    });
  });
});

app.use('/api', router);
