// Generated by CoffeeScript 1.7.1
var Bear,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Bear = (function(_super) {
  __extends(Bear, _super);

  function Bear() {
    return Bear.__super__.constructor.apply(this, arguments);
  }

  Bear.prototype.defaults = {
    name: 'Jorge',
    occupation: 'developer'
  };

  return Bear;

})(Backbone.Model);
